# Site settings
title: Norberto Herz
header-img: img/header-background.jpg
header-img-blur: img/header-background-blur.jpg
description: "Norberto Herz's professional portfolio"
url: "http://nohorbee.github.io/"
twitter_username: nohorbee
github_username:  nohorbee
facebook_username:  nohorbee

# Posts settings
excerpt_separator: <!--MORE-->

# Build settings
markdown: kramdown
#kramdown:
#  input: GFM
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#Multilingual
languages: ['es', 'en']
